#!/bin/sh
#
# Xcode Cloud post-clone hook.
#
# The Xcode project is generated by XcodeGen from `project.yml` and is NOT
# committed (see .gitignore: `*.xcodeproj`). Xcode Cloud builds from the cloned
# repository, so the `.xcodeproj` and its shared `HighRise` scheme don't exist
# until we generate them here — this runs right after the clone and before the
# build resolves the scheme.
#
set -e

# Skip Homebrew's slow auto-update; the runner already has a recent Homebrew.
export HOMEBREW_NO_AUTO_UPDATE=1

# Install XcodeGen (a no-op that exits 0 if it's already present on the runner).
brew install xcodegen

# Generate the project + scheme at the repo root, where project.yml lives.
cd "$CI_PRIMARY_REPOSITORY_PATH"
xcodegen generate
